# Generated by Django 3.0.8 on 2020-07-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200705_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isBn',
            field=models.CharField(help_text='Search In Google To Find More About It..', max_length=13, verbose_name='ISBN'),
        ),
    ]
